version: ">= 0.14.0"

formatter: markdown table

content: |-
  # Terraform Network-as-Code Cisco FMC Module

  A Terraform module to configure Cisco FMC.

  ## Usage

  This module supports an inventory driven approach, where a complete FMC configuration or parts of it are either modeled in one or more YAML files or natively using Terraform variables.

  ## Examples

  Configuring a Network-group Object using YAML:

  #### `data/existing.nac.yaml`

  ```yaml
  {{ include "./examples/network_groups/existing.nac.yaml" }}
  ```

  #### `data/fmc.nac.yaml`

  ```yaml
  {{ include "./examples/network_groups/fmc.nac.yaml" }}
  ```

  #### `main.tf`

  ```hcl
  {{ include "./examples/network_groups/main.tf" }}
  ```

  {{ .Requirements }}
  {{ .Inputs }}
  {{ .Outputs }}
  {{ .Resources }}
  {{ .Modules }}
output:
  file: README.md
  mode: replace

sort:
  enabled: true
  by: required
