version: ">= 0.14.0"

formatter: markdown table

content: |-
  # FMC Host Object Example

  Set environment variables pointing to FMC:

  ```bash
  export FMC_USERNAME=admin
  export FMC_PASSWORD=Cisco123
  export FMC_HOST=https://10.1.1.1
  ```

  To run this example you need to execute:

  ```bash
  $ terraform init
  $ terraform plan
  $ terraform apply
  ```

  Note that this example will create resources. Resources can be destroyed with `terraform destroy`.

  #### `host.yaml`

  ```yaml
  {{ include "./host.yaml" }}
  ```

  #### `main.tf`

  ```hcl
  {{ include "./main.tf" }}
  ```

output:
  file: README.md
  mode: replace
