version: ">= 0.14.0"

formatter: markdown table

content: |-
  # FMC Network Group Object Example

  This example will create new `MyNetworkGroup1`, `MyNetworkGroup2` network-group objects that contains two objects:
  > `MyNetworkGroup1`:
  - newly created `MyHost1` host object
  - already existing `any-ipv4` network object
  > `MyNetworkGroup2`:
  - newly created `MyNetworkGroup1` network-group object
  - newly created `MyHost2` host object


  Set environment variables pointing to FMC:

  ```bash
  export FMC_USERNAME=<username>
  export FMC_PASSWORD=<password>
  export FMC_URL=https://<hostname>
  ```

  To run this example you need to execute:

  ```bash
  $ terraform init
  $ terraform apply
  ```

  Note that this example will create resources. Resources can be destroyed with `terraform destroy`.

  #### `data/existing.nac.yaml`

  ```yaml
  {{ include "./existing.nac.yaml" }}
  ```

  #### `data/fmc.nac.yaml`

  ```yaml
  {{ include "./fmc.nac.yaml" }}
  ```

  #### `main.tf`

  ```hcl
  {{ include "./main.tf" }}
  ```

output:
  file: README.md
  mode: replace
